### ISSUE TITLE
Problems with unlimited elements

### ISSUE THREAD

**Issue by calculorotina** [sudharsank/spfx-demos#1]
hi guys.

i have problem with loading gallery imagem in loop archive it gives me the error in line 414 with the following code:
I´m using wordpress oceanwp with the unlimited elements for elementor

    public function load($name)
    {
        if ($name instanceof TemplateWrapper) {
            return $name;
        }

        if ($name instanceof Template) {
            return new TemplateWrapper($this, $name);
        }

        return new TemplateWrapper($this, $this->loadTemplate($name));
    }

**Comment by calculorotina** [comment]
[unitecreator_template_engine.class.zip](https://github.com/sudharsank/spfx-demos/files/6137017/unitecreator_template_engine.class.zip)

[logs.zip](https://github.com/sudharsank/spfx-demos/files/6136940/logs.zip)

**Comment by sudharsank** [comment]
Hi @calculorotina, the issue mentioned is not clear. Can you please be more specific and also post the issue that you encounter because of the repo or from any of the demo samples included.
